### PR TITLE
Code reorganisation

### PR DESCRIPTION
**Pull request by MickdeGraaf**
- Laid down a basic organisation for components
- Use props.children instead of a custom prop for text in ui components

### CODE REVIEW

**Comment by Alexintosh** [comment]
I find having more than 2 levels of hierarchy in folders unnecessary and I know for a fact it becomes bananas very soon. I don't have much time to explain in this comment but there is tons of literature on the why. Let's use enterprise-level conventions, there are reasons why the work best.

Folders in `components` should not be separated by pages. 

The ideal structure is:
```
/components/single-component
/pages/single-page
```

https://medium.com/hackernoon/the-100-correct-way-to-structure-a-react-app-or-why-theres-no-such-thing-3ede534ef1ed

**Review by Alexintosh — CHANGES_REQUESTED** [review]
see my comments in the PR

**Comment by Alexintosh** [comment]
+1 for props.children

**Comment by MickdeGraaf** [comment]
I think it's better to close this one and do the improvements again based on the master branch. Solving these conflicts would be more work than doing the improvements again.

**Pull request closed without merging**
