### PR TITLE
adding error notification for wrong network

### PR DESCRIPTION
**Pull request by dmvt**
##### Checklist

- [X] Changes don't break existing behavior
- [X] Tests coverage hasn't decreased

### CODE REVIEW

**Comment by dimarconicola** [comment]
The message is correct on the notification but it's still wired on the modal. wdyt @dmvt 

Screenshot 2020-02-18 at 14 10 19

**Review by dimarconicola — APPROVED** [review]

**Comment by dmvt** [comment]
Very weird... I saw it as changed :/

Personally I think this is fine for the moment. We could also just remove the message on the modal altogether and disable the wallet button on the wrong network

**Review by MickdeGraaf — COMMENTED** [review]
Looks good to me.

**Review by MickdeGraaf — APPROVED** [review]

**Comment by MickdeGraaf** [comment]
image
Network error is shown when opening the website in a browser without Metamask installed

**Pull request merged**
